archetypeDir = "blog/archetypes"
baseURL = "https://blog.ypertex.com/"
contentDir = "blog/content"
copyright = "Some rights reserved"
dataDir = "blog/data"
languageCode = "en-us"
paginate = 8
paginatePath = ""
preserveTaxonomyNames = true
publishDir = "blog/published"
staticDir = "blog/static"
theme ="inhabitu-hugo"
title = "Ypertex Blog"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params]
cloudinaryURL = "https://res.cloudinary.com/ypertex/image/upload/"
cover = "ypertex-blog-cover.png"
description = "Design. Technology. Future."
license = "Creative Commons Attribution 4.0 International License (CC BY 4.0)"
licenseURL = "http://creativecommons.org/licenses/by/4.0/"
github = "Ypertex/blog"
mainLogo = "ypertex-logo-2017-01.png"
navLogo = "ypertex-logo-2017-01-inverted.png"
privacyNoticeURL = "/privacy/"
twitter = "Ypertex"

[privacy]
    [privacy.twitter]
        disable = false
        enableDNT = true
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[taxonomies]
author = "authors"
tag = "tags"

[related]
threshold = 50
includeNewer = true
toLower = true
  [[related.indices]]
  name = "tags"
  weight = 40.0
  [[related.indices]]
  name = "title"
  weight = 40.0
  [[related.indices]]
  name = "summary"
  weight = 10.0
    [[related.indices]]
  name = "date"
  weight = 10.0